### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by mr-White** [kentcdodds/ng-stats#46]
When trying to add and run ngStats on my angularJS 1.4.x app, I get an Uncaught TypeError. It use to work for me in the past... I tried a fresh copy of ngstats.js from the repo too. I tried using the snippets and bookmarks method.

[Screenshot of Console Error](http://puu.sh/jYXPS/48405db699.png)
[Screenshot of Line of Code the Console Error Pointed Too](http://puu.sh/jYXTE/7b3e9c8b29.png)

**Comment by kentcdodds** [comment]
It looks like the `getRootScope()` is returning `null` or `undefined`. This is likely because you don't have `debugInfo` enabled in your app. Try running [`angular.reloadDebugInfo()`](https://docs.angularjs.org/guide/production#disabling-debug-data) to enable that debug info in your app, then load ng-stats.

**Comment by tinyfly** [comment]
Co-worker of @mr-White here. That worked. Though an interesting note. We were also running this through browserSync and using `angular.reloadDebugInfo()` with that still gave me the same error. So if I stop browserSync and just run normal localhost then it seems to work fine.

**Comment by kentcdodds** [comment]
Don't know what to tell you... I don't think that there's much I can do about that. Most of the time I use this when I have debug info enabled (in development). You should probably not disable debug info during development.

Because there's nothing I can do on the ng-stats side of things, I'm going to close this.
